### ISSUE TITLE
Remove support for classic changelog format

### ISSUE THREAD

**Issue by felixfontein** [ansible-community/antsibull-changelog#137]
That format is used by Ansible 2.9 (and nothing else to my knowledge). It has been deprecated in 0.21.0 (released on 2023-06-27).

If a new relase of Ansible 2.9 should be done, an older version of antsibull-changelog still supporting that format can be used. IMO there's no need to carry around the extra complexity.

**Comment by samccann** [comment]
@felixfontein  - I was poking away at this one and removing all classic support, but then I noticed [this in the docs](https://ansible.readthedocs.io/projects/antsibull-changelog/changelog-configuration/#changes_format-string) about the ``changes_format``:
```
Note that support for `classic` is **DEPRECATED** and will be removed in
a future release. The field will from then on be required.
```
So does that mean we need to keep that parameter around even though it can only ever be ``combined`` once classic support is removed? Or can we just get rid of it entirely?

**Comment by felixfontein** [comment]
@samccann that parameter should stay around for some time, and make the program fail if set to anything else than `combined`. That ensures that new versions of antsibull-changelog aren't accidentally used with projects using the old format that it no longer supports.
