### ISSUE TITLE
Specifying an output file and a specific output format on the CLI is broken when multiple output formats are configured

### ISSUE THREAD

**Issue by Callum027** [ansible-community/antsibull-changelog#149]
I'm using the latest version and have both Markdown and RST configured in my `changelog/config.yml`. I get the following error when specifying both `--output` and `--output-format` to generate release notes for a specific version to a custom file:

```
callum@callum-laptop:~/dev/github.com/Callum027/ansible-collection-palworld-dedicated-server$ antsibull-changelog generate 2.1.0 --only-latest --output RELEASENOTES.md --output-format md
When an explicit output path is specified and more than one output format is configured, you need to explicitly specify an output format
```

[Looking at the relevant code](https://github.com/ansible-community/antsibull-changelog/blob/0232c1e3099c4e45a83dae4fa6dd5b151df5dbc7/src/antsibull_changelog/cli.py#L753-L758), it appears to not take into account the `--output-format` argument value at all.

**Comment by felixfontein** [comment]
Oops! Thanks for reportig this!

**Comment by felixfontein** [comment]
#151 fixes this.
