### ISSUE TITLE
Is generated changelog supposed to end up inside changelogs dir?

### ISSUE THREAD

**Issue by geerlingguy** [ansible-community/antsibull-changelog#19]
When I generate a changelog, the `CHANGELOG.rst` file is placed inside the `changelogs` subdirectory of the collection, and not in the collection root.

Typically people look for a `CHANGELOG` file (bare, .txt., .md, whatever) in the root of a project, so it seems like that would be a better default. But I wasn't sure if there was a particular reason the RST file isn't placed in the root...

**Comment by felixfontein** [comment]
The main reason is that it does pretty much what the old changelog generator used to do in ansible/ansible. It definitely makes sense to move the generated .rst file one level up though :) You can probably get this (haven't tried) by prepending `../` to the `changelog_filename_template` value in `changelogs/config.yaml`.

**Comment by geerlingguy** [comment]
Yep, that worked!

**Comment by felixfontein** [comment]
resolved_by_pr #21
