### ISSUE TITLE
antsibull_changelog skips certain fragments

### ISSUE THREAD

**Issue by NilashishC** [ansible-community/antsibull-changelog#46]
##### SUMMARY
While generating the changelog for a release, if there's a fragment with the same name as a fragment from a previous release, the current one isn't picked up.

##### ISSUE TYPE
- Bug Report

##### VERSION
```
Name: antsibull-changelog
Version: 0.7.0
Summary: Changelog tool for Ansible-base and Ansible collections
Home-page: https://github.com/ansible-community/antsibull-changelog
Author: Felix Fontein
Author-email: felix@fontein.de
License: GPL-3.0-or-later
Location: /Users/nchakrab/venvs/dev/lib/python3.6/site-packages
Requires: semantic-version, rstcheck, packaging, PyYAML, docutils
Required-by: antsibull
```

##### STEPS TO REPRODUCE
- Add a changelog fragment with the same name as fragment from previous release (which is not present now but has an entry in changelog.yaml).
- Run `antsibull-changelog release --version x.x.x`

##### EXPECTED RESULTS
The current fragment is read and added in the correct sections in both CHANGELOG.rst and changelog.yaml

##### ACTUAL RESULTS
The current fragment with the same name as fragment from previous release is not read.

**Comment by felixfontein** [comment]
Will be resolved by #47.
