### ISSUE TITLE
Make the tool failing by default when changelog/fragments/X.Y.Z.yml is missed

### ISSUE THREAD

**Issue by Andersson007** [ansible-community/antsibull-changelog#53]
Make the tool failing by default when changelog/fragments/X.Y.Z.yml is missed

When releasing, I put `XYZ.yml` in the `changelog` directory (not in `changelog/fragments/`) by mistake .
Then ran the tool. It calmly finished. Then I noticed that there was no the `Release notes` section in `changelog/CHANGELOG.yml`.

I think it could check the file and fail if it's missed.

**Comment by felixfontein** [comment]
There is no requirement to have a release summary, and also no requirement that it should be named exactly that. I don't think it's the changelog generator's job to check on these things.

What I think would be ok is to emit a warning on `antsibull-changelog release when no `release_summary` section is found.

**Comment by Andersson007** [comment]
yeah, the warning is also fine, thanks!
