### ISSUE TITLE
init changelog config should be in proper yaml

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible-community/antsibull-changelog#91]
Added changelog to a new collection then ran ansible-lint against it. Had the following errors:
```
WARNING  Listing 5 violation(s) that are fatal
changelogs/config.yaml:1: yaml[document-start]: Missing document start "---"
changelogs/config.yaml:14: yaml[indentation]: Wrong indentation: expected 2 but found 0
changelogs/config.yaml:32: yaml[document-end]: Missing document end "..."
Error: Missing document start "---"
Error: Wrong indentation: expected 2 but found 0
Error: Missing document end "..."
```
This should be updated to be proper yaml.

**Comment by felixfontein** [comment]
How do you define "proper YAML"? All YAML parsers I know off don't require the above things your linter mentioned.

**Comment by sean-m-sullivan** [comment]
Let me check it on whats enabled in ansible-lint Prod profile, as this is an Ansible Tool, that is what it should adhere to.

**Comment by djdanielsson** [comment]
its in our yaml lint rules

**Comment by felixfontein** [comment]
Closing since this seems more like a problem with ansible-lint or yamllint.

**Comment by gotmax23** [comment]
We use PyYAML to dump yaml files. The indentation linting errors are from that. ruamel.yaml does handle this properly, but I don't think this on its own is a compelling reason to switch yaml libraries and pull in another dependency. Fix these linting errors by hand if you'd like or just add that file to the linter's ignore list. The file is still perfectly valid yaml.

It would be trivial to add `---` document starts, though. @felixfontein, wdyt?

**Comment by felixfontein** [comment]
I don't see why it is necessary, but that would be possible.

**Comment by sean-m-sullivan** [comment]
Let me get back to this, as I think some of it was our own rules, and some of it was ansible lint. if its done with the pyaml dump thats fine, just thought we should be putting out things that eat our own dogfood with ansilbe-lint.

**Comment by djdanielsson** [comment]
the requirement of the --- and ... is in our rules because it is correct yaml syntax but is not part of the production profile so I think it is most likely fine to just leave it how it is because most people don't seem to care about requiring --- and ...
